### PR TITLE
Upgrade to the latest Micropython Radio API

### PR DESCRIPTION
**Pull request by niutech**
First of all, thank you for your very simple yet addictive space shoot multiplayer game! In order to run it with the latest [Micropython Radio API](https://microbit-micropython.readthedocs.io/en/latest/tutorials/radio.html), it had to be slightly modified, so I am submitting this PR.

What's the license of this file? Can I extend it by adding high scores, etc.?

### CODE REVIEW

**Comment by c-mart** [comment]
Hi @niutech, you are welcome! To be honest I've forgotten about all this for 4 years. I dug out my micro:bits, upgraded firmware, tested your code, and it works, so thank you for the fix :) Happy to see the radio module now part of the mainline firmware. It means this could be PRed upstream or something.

The license is MIT / BSD / do whatever you like with the code. It belongs to everyone.

**Comment by c-mart** [comment]
Also @niutech, if you know someone who is in need of a couple of micro:bits (with breakout boards and AAA battery holders), I would be happy to ship them from northeastern USA. @ntoll gave me two of his, and I've done very little with them since mid-2016. I cannot guarantee they are free of germs (I am close to someone who may have symptoms and is waiting for test results), but I could wait until a negative result or immunity to package and send (and/or the receipient could age the box for a few days on the porch or for a much shorter period in the oven).

**Comment by ntoll** [comment]
@c-mart :wave: (your mention just ended up with an alert in my inbox - hope all well given current pandemic situation)

**Comment by niutech** [comment]
@c-mart Thanks for merging. I made another PR for restarting the game and counting the score.

As for the Micro:bit, I am making Polish educational platform [Koduś](https://kodus.pl) so I would like to buy them, but the problem is with shipping - I live in Poland.

**Pull request merged**
